[package]
name = "log_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"

log = "0"
log4rs = "1"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14"
